# Maven
name: ContinuousDelivery

trigger:
  branches:
    include:
      - master
      - develop

pr: none

steps:
- task: UseNode@1
  inputs:
    version: '12.x'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'HEROKU_API_KEY=$(HEROKU_API_KEY) heroku:deploy-war'
